version: '3.8'

services:

  api:
    build: .
    container_name: agenda_pro_api
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db


  db:
    image: postgres:15-alpine
    container_name: agenda_pro_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=agendapro
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
